### PR TITLE
defs: Fix 4.3.4.15595 incorrect Difficulty DBC ref

### PR DESCRIPTION
**Pull request by HelloKitty**
Difficulty DBC doesn't exist in Cata.

### CODE REVIEW

**Comment by HelloKitty** [comment]
Sorry for the mediocre commit name.

**Comment by bloerwald** [comment]
Hey, thanks. Before I merge this, to be sure:

Does the table not exist or are the values also different? If the values are identical we usually assume an existing but unshipped table, and reference that virtual table: it still is a reference to that table semantically, and them shipping or not shipping it is not a change to the format of this table.

**Comment by HelloKitty** [comment]
@bloerwald I cannot comment on the values themselves. Maybe it would be what would be expected in a hypothetical Difficulty DBC if it existed during these versions. On wow.tools these foreign keys don't properly link to anything on these versions since the DBC doesn't exist.

It's up to you if you want to merge it because even if you don't merge it there is still an inconsistency with the WOTLK/3.x defintions then which refer to it as Difficulty and not DifficultyID. So if you want the defs to refer to tables that existed or were shipped in future versions then maybe the 3.x defs should be updated.

**Comment by bloerwald** [comment]
Your change is correct: [In 4.3.4, Sinestra has Difficulty = 2/3](https://wow.tools/dbc/?dbc=dungeonencounter&build=4.3.4.15595#page=1&search=Sinestra). In [5.0.3 it has DifficultyID = 5/6](https://wow.tools/dbc/?dbc=dungeonencounter&build=5.0.3.15882#page=1&search=Sinestra), which is *clearly* not the same value, and also [Difficulty.OldEnumValue = 2 for Difficulty.ID = 5 and Difficulty.OldEnumValue = 3 for Difficulty.ID = 6](https://wow.tools/dbc/?dbc=difficulty&build=5.0.3.15882#page=1&colFilter[2]=2&colFilter[6]=heroic). It was indeed a bad name in the definitions and MoP was the version to introduce that table, also server side.

Thanks for the contribution!

**Comment by HelloKitty** [comment]
> Your change is correct: [In 4.3.4, Sinestra has Difficulty = 2/3](https://wow.tools/dbc/?dbc=dungeonencounter&build=4.3.4.15595#page=1&search=Sinestra). In [5.0.3 it has DifficultyID = 5/6](https://wow.tools/dbc/?dbc=dungeonencounter&build=5.0.3.15882#page=1&search=Sinestra), which is _clearly_ not the same value, and also [Difficulty.OldEnumValue = 2 for Difficulty.ID = 5 and Difficulty.OldEnumValue = 3 for Difficulty.ID = 6](https://wow.tools/dbc/?dbc=difficulty&build=5.0.3.15882#page=1&colFilter%5B2%5D=2&colFilter%5B6%5D=heroic). It was indeed a bad name in the definitions and MoP was the version to introduce that table, also server side.
> 
> Thanks for the contribution!

Oh, you dug deep into it! Well, glad it was a helpful PR in the end.

**Pull request merged**
