### PR TITLE
Update BeckonTrigger.dbd

### PR DESCRIPTION
**Pull request by Dorovon**
The new field could have been added in a 10.0.7 build prior to 10.0.7.48295, but I do not have copies of this DB2 from before then. Additionally, I have no copies prior to 10.0.5.48317, so it's possible there are more layout hashes to be added.

### CODE REVIEW

**Comment by Marlamin** [comment]
Can you add the build you checked (probably the one you mentioned) with a `BUILD` after the `LAYOUT` line in the layout you added?

**Comment by Dorovon** [comment]
Sure, will do.

**Comment by Dorovon** [comment]
I also added two missing LayoutHashes to CharacterFaceBoneSet.dbd, since I checked all of the DBDs for the latest 10.1 build and noticed it was missing a definition as well.

**Comment by Marlamin** [comment]
Excellent, thanks!

**Pull request merged**
