### PR TITLE
defs: normalise unknown field names

### PR DESCRIPTION
**Pull request by barncastle**
Normalise all unknown field names to the `Field_lowset_build_with_underscores` standard to make life easier and to fix my ocd. This also applies to the `Padding_xxxxxxxx` fields..

I've taken the Bernd standard and applied the `Field_x_x_xxxxx_xxx_additionalinfo` approach where appropriate too

### CODE REVIEW

**Comment by Marlamin** [comment]
Good stuff! Thanks.

**Comment by Marlamin** [comment]
After a talk with bernd, for future reference we should probably verify these columns were actually added in that version instead of it just being the first version DBD sees them in. Might become an issue in the future when we start adding more versions. Not a huge issue right now but something to keep in mind if we do this again.

**Comment by barncastle** [comment]
Totally agree. Part of the point of this PR was just so my tool chain works
on these older defs.

At somepoint we need to go back and revisit all unnamed columns and map
everything retrospectively (and maybe pseudo name everything) but to do
that we need the full alpha to legion..

On an aside, I was thinking about revisiting pre-wod over the coming week
and getting that fixed and merged. I'll get in touch about that separately.

**Comment by Marlamin** [comment]
Sounds good!

**Pull request merged**
