### PR TITLE
Update ChrRaces with official names

### PR DESCRIPTION
**Pull request by funjoker**

### CODE REVIEW

**Comment by Marlamin** [comment]
Did you verify if this is the right way around? Expected the S in RS to mean short and the L in RL to mean lore but in version definitions these are switched around now.

**Comment by Marlamin** [comment]
Not saying it's wrong btw, just not sure. Here's an excerpt from the mobile app to verify:

```
Lore_name       Short_name
Human           Human
Orc             Orc
Dwarf           Dwarf
Kaldorei        Elf
Forsaken        Undead
Shu'halo        Tauren
Gnome           Gnome
Darkspear       Troll
Bilgewater      Goblin
Sin'dorei       Elf
Draenei         Draenei
```

**Comment by funjoker** [comment]
Short is all trolls are named troll. Lore for trolls are darkspear or zandalari. Same for void elves, panderen etc.

**Comment by bloerwald** [comment]
> Expected the S in RS to mean short and the L in RL to mean lor

Yeah, my reversing was reversed. You can see the code in that other issue

**Comment by Marlamin** [comment]
> > Expected the S in RS to mean short and the L in RL to mean lor
> 
> Yeah, my reversing was reversed. You can see the code in that other issue

bernd ur fired (and rehired please dont leave)

**Pull request merged**
