### PR TITLE
getexe.lua

### PR DESCRIPTION
**Pull request by ferronn-dev**

### CODE REVIEW

**Comment by Marlamin** [comment]
If this is for something automated like a GitHub action for updating definitions I would suggest against using a product => executable map as some products (namely wowz, wowlivetest and whatever I'm not thinking of) sometimes switch between live, PTR or beta executables.

This is the list WoW.tools currently uses:
```
$targets = [
        // Mainline
        "Wow.exe", "WowT.exe", "WowB.exe", 
        // Classic
        "WowClassic.exe", "WowClassicT.exe", "WowClassicB.exe", 
        // Old 64-bit specific builds
        "Wow-64.exe", "WowT-64.exe", "WowB-64.exe"    
    ];
```

It loops over install entries and extracts the first one it finds from that list.

**Comment by ferronn-dev** [comment]
At this point no; I'm just trying to get a baseline before building any more complicated infrastructure.

**Comment by ferronn-dev** [comment]
This lets me actually run the DBDefsDumper from within the devcontainer, which I couldn't do before.

**Review by Marlamin — APPROVED** [review]
Alrighty, all good then.

**Pull request merged**
