### PR TITLE
issue #13 - let unk_8c/90 comments be an annotation

### LINKED ISSUE #13: unk_8c/unk_90 flags are parent columns
from https://github.com/wowdev/renderservice/issues/10 via @Shauren:

```c++
    bool HasParentLookup;
    uint ParentIdColumn;
    uint ParentIdHotfixColumn;
```

- [x] sed those comments to be an annotation, e.g. `$parent$` in the defs we have (only known for 8.0.1)

### PR DESCRIPTION
**Pull request by bloerwald**
fixes #13

### CODE REVIEW

**Comment by bloerwald** [comment]
yeah, don't merge yet. this and relation should probably be understood before merging. I thought I somewhat did, but likely I didn't.

**Comment by bloerwald** [comment]
```
$ for dbd in *; do printf "%32s %8s %6s\n" ${dbd/.dbd/} "$(grep -q relation $dbd && echo relation)" "$(grep -q unk_90 $dbd && echo parent)"; done | grep 'relation parent' | wc -l
       0
```

Not a single table has both, relation and parent. So if they would be the same thing, Blizzard has both, implicit and explicit such columns, which sounds unlikely. Yet, the column names tagged respectively sound similar ._.

## list of relation columns

alliedRaceID animEnumID areaGroupID areaPoiID areaTableID artifactID
artifactPowerID azeritePowerSetID azeriteTierUnlockSetID battlePetAbilityID
battlePetBreedID battlePetSpeciesID bountySetID CameraEffectID
chrSpecializationID chrSpecID chrUpgradeBucketID chrUpgradeTierID class classID
creatureDisplayInfoID creatureID criteriaTreeID currencyTypeID declinedWordID
emotesTextID fileDataID gameObjectDiffAnimID gameObjectDisplayInfoID
GameObjectsID garrEncounterID garrEncounterSetID garrFollItemSetID
garrFollowerID garrFollowerSetID garrMechanicSetID garrMissionID
garrMissionSetID glyphPropertiesID GMSurveyQuestionID helmetGeosetVisDataID
itemContextPickerID itemDisplayInfoID itemID itemSetID journalEncounterID
journalEncounterItemID journalEncounterSectionID lfgDungeonsID lvl
managedWorldStateID mapDifficultyID mapID mountID movieID multiPropertiesID
npcModelID Parent parentAnimKitConfigID parentAnimReplacementSetID
parentILSQualitySetID parentItemBonusTreeID parentItemID
parentItemLimitCategoryID parentSpellVisualKitID ParentWeatherID phaseGroupID
playerWorldMapAreaID questID QuestPOIBlobID raceID rewardPackID
scheduledWorldStateID SoundAmbienceID soundFilterID spellAuraVisibilityID
spellFlyoutID spellID spellProcsPerMinuteID spellVisualID
spellVisualMissileSetID srcCreatureDisplayInfoID TransportID uiModelSceneID
vehicleUIIndicatorID weaponTrailID WMOID worldMapAreaID zoneLightID

## list of parent columns

artifactAppearanceSetID artifactID battlePetAbilityID battlePetAbilityTurnID
characterLoadoutID classID containerID ContinentID factionID fileDataID
friendshipRepID FromTaxiNode garrAbilityID garrBuildingID garrSiteLevelID
garrTalentTreeID itemID itemType journalEncounterID journalTierID lightParamID
managedWorldStateInputID mapAreaID mapID materialResourcesID modelResourcesID
mountTypeID ownerID parentAnimKitID parentItemBonusListID parentSoundKitID
parentTransmogSetID PathID pvpScalingEffectTypeID RaceID scenarioID
sceneScriptPackageID scheduledWorldStateGroupID skillID skillLine SoundBusID
soundEmittersID soundKitID specID spellID transmogSetID ui_order WMOID
WorldMapAreaID

**Comment by MMOSimca** [comment]
So I was really confused by this at first, but I think I understand what's going on here.

The section we call 'relationship_data' in DB2s sometimes has its data exclusively in that structure and not in the records in the DB2. In those cases, we are using the 'relation' attribution. An example of this is BattlePetSpeciesXAbility::BattlePetSpeciesID.

Other times though, the 'relationship_data' section has information that is duplicated completely by the a field in the records in the DB2. An example of this is Achievement::UIOrder. The column is the relationship_data structure and it is also the final column of the records. I just assumed in these cases relationship_data was useless for our purposes and that the client probably didn't track it, so we shouldn't bother either. But it must, in order to use the structure for its quicker loading, and schlumpf says that the client keeps explicit, separate information about this type of column. This means it needs its own name.

I don't know if 'parent' is really a reasonable name, even if Blizzard does use it. Maybe something like... 'alternateIndex'? I don't know; I don't want to go too complex, and I also don't want to confuse it with unique index when/if we add that (I haven't been keeping up, idk if we have that already or not).

**Comment by bloerwald** [comment]
now:

- `annotation` is a comma-separated list of annotations (rather than just one)
- `relation` is `noninline`, `relation`.
- `parent` is `relation`.

I hope this does mirror the real thing finally.

**Pull request merged**
